#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# python /app/manage.py collectstatic --noinput

{%- if cookiecutter.use_async == 'y' %}
exec uvicorn config.asgi:application --host 0.0.0.0 --port 5000 --proxy-headers --app-dir /app
{%- else %}
exec gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
{%- endif %}
